### ISSUE TITLE
[Offtopic] Netwalk

### ISSUE THREAD

**Issue by Vistaus** [theBest3000/Wallpapers#10]
Hi,

I'm sorry to open an offtopic issue here, but I couldn't find any other way to contact you. It seems like you've been busy repackaging/updating some UT apps, which is great! :) One app that I would like to return to UT is UBPorts Netwalk. It was available until some time last year, but then it wasn't anymore and it stopped working altogether. Here's the link to the last packager: https://open-store.io/app/uports-netwalk.mateo-salta
It seems to be based on the code from https://code.launchpad.net/~flscogna/ubuntu-netwalk/trunk

I really miss playing this game on the go and when I'm bored, so I would love it if you could re-publish it :) I'd even be willing do a generous donation if you could get it done :)

**Comment by theBest3000** [comment]
Hi.
Have you tried contacting the owner of the app? The game works perfectly on my tablet. Have you switched your phone?

**Comment by Vistaus** [comment]
I can't contact the owner.

I have not switched my phone. It's not available at all anymore in the OpenStore since the latest OTA. Also, it's not just my phone: if you look at the comments section, you can see that someone else can't install it on his Volla Phone either. So the app really does need updating.

**Comment by theBest3000** [comment]
I see. The problem is that the source code you pointed me at is very old. I will see what I can do. Can you please tell me, which phone your are using?

**Comment by Vistaus** [comment]
Thanks for looking into it :)
I'm using a Poco F1 (for which Ubuntu Touch is available through Halium and GSI).

**Comment by theBest3000** [comment]
I found the maintainer of the game: https://github.com/mateosalta/uports-netwalk

**Comment by Vistaus** [comment]
Looks like he uploaded the code yesterday on GitHub. Thanks for the find - I'll close this now :)
